/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
 feature/my_feature_4
        System.out.println("Hello World! - my_feature_4");

        System.out.println("Hello World! - feature ");
 master
        return true;
    }
}
