/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello World! - feature 4");
        return true;
    }
}
